---
- name: "Copy the kubernetes repository file"
  copy:
    src: "kubernetes.repo"
    dest: /etc/yum.repos.d/kubernetes.repo
    owner: root
    group: root
    mode: '0644'
  become: true

- name: "Disable Selinux"
  selinux:
    state: disabled
  become: true
  register: selinux

- name: "Reboot if required"
  reboot:
    msg: "Rebooting after disabling selinux"
  when: selinux.reboot_required
  become: true

- name: "Install Kubernetes binaries"
  yum:
    name: "{{ item }}"
    disable_excludes: kubernetes
    state: present
  loop:
  - "kubelet{% if node.kubernetes.version is defined %}-{{ node.kubernetes.version }}{% endif %}"
  - "kubeadm{% if node.kubernetes.version is defined %}-{{ node.kubernetes.version }}{% endif %}"
  - "kubectl{% if node.kubernetes.version is defined %}-{{ node.kubernetes.version }}{% endif %}"
  become: true
  notify: "Start and Enable Kubelet"

- name: "Ensure kubelet is started"
  meta: flush_handlers
