---
- name: Install Kubernetes on master nodes
  hosts: master
  vars:
    cri:
      docker: true
    node:
      is_master: true
      kubernetes:
        version: 1.19.0
  tasks:
    - name: "Include k8s-cluster/"
      include_role:
        name: "k8s-cluster/"

- name: Install Kubernetes on worker nodes
  hosts: worker
  vars:
    cri:
      docker: true
    node:
      is_worker: true
  tasks:
    - name: "Include k8s-cluster/"
      include_role:
        name: "k8s-cluster/"
