---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: master
    image: pycontribs-centos7-docker:latest
    dockerfile: Dockerfile.j2
    build_image: true
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
    privileged: true
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup:ro
    - /lib/modules:/lib/modules:ro
  - name: worker
    image: pycontribs-centos7-docker:latest
    dockerfile: Dockerfile.j2
    build_image: true
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
    privileged: true
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup:ro
    - /lib/modules:/lib/modules:ro
provisioner:
  name: ansible
  # env: 
  #   MOLECULE_NO_LOG: false
scenario:
  name: default
verifier:
  name: ansible
lint: |
  set -e
  ansible-lint
  flake8
